version: '3.5'
services:
  portafolio:
      build:
        context: .
        dockerfile: Dockerfile
      image: 'portafolio:latest'
      container_name: portafolio
      restart: always
    #   volumes:
    #       - 'cv:/var/www/html/cv'
      networks:
          - proxy
# volumes:
#   cv:
networks:
    proxy:
        name: proxy
        external: true

